name: bayti
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  ## App Packages ##

  # State management:
  get: ^4.6.6

  # Dart
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Remote storage
  dio: ^5.5.0+1

  # Local storage
  get_storage: ^2.1.1

  # Responsive design
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3

  # Date time & localization
  intl: ^0.19.0

  # check connection
  connectivity_plus: any

  # Map google
  google_maps_flutter: ^2.7.0

  # Image
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  flutter_svg: any
  cached_network_image: ^3.3.1
  flutter_cache_manager: any

  # Loading
  flutter_spinkit: ^5.2.1

  # Back4app sdk
  parse_server_sdk_flutter: 8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application :
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/svgs/

    # To add fonts to your application :
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 300
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 700
